version: '3.8'

services:
  api-agendamentos:
    image: node:latest
    container_name: api-agendamentos
    restart: always
    working_dir: /api-agendamentos
    volumes:
      - /home/redig/github/redig/faculdade-agendamento-medico-online/api-agendamentos:/api-agendamentos
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - agendamentos_network
      - postgres16_postgres16_network
    stdin_open: true
    tty: true
    command: >
      sh -c "npm install && npx prisma generate && npx prisma migrate deploy && node index.js"

  redis:
    image: redis:latest
    container_name: redis-agendamentos
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - agendamentos_network

volumes:
  redis_data:

networks:
  agendamentos_network:
    external: true
  postgres16_postgres16_network:
    external: true
